const fields = 'id,candidate_id,name,aliases,description,content,image,historical_use,current_use,position_x,position_y,source_url,source_name,evidence,review_status,status,sort_order,created_at,updated_at'
function where(filters, publicOnly) { const conditions = []; const values = []; if (publicOnly) conditions.push("review_status = 'verified'", 'status = 1'); if (filters.keyword) { conditions.push('(name LIKE ? OR description LIKE ? OR historical_use LIKE ?)'); values.push(...Array(3).fill(`%${filters.keyword}%`)) } if (filters.reviewStatus) { conditions.push('review_status = ?'); values.push(filters.reviewStatus) } if (filters.status !== undefined) { conditions.push('status = ?'); values.push(filters.status) } return { clause: conditions.length ? `WHERE ${conditions.join(' AND ')}` : '', values } }
async function list(db, filters, page, publicOnly = false) { const f = where(filters, publicOnly); const [rows] = await db.query(`SELECT ${fields} FROM courtyard ${f.clause} ORDER BY sort_order,id LIMIT ? OFFSET ?`, [...f.values, page.pageSize, page.offset]); return rows }
async function count(db, filters, publicOnly = false) { const f = where(filters, publicOnly); const [rows] = await db.query(`SELECT COUNT(*) AS total FROM courtyard ${f.clause}`, f.values); return rows[0].total }
async function find(db, id, publicOnly = false) { const [rows] = await db.query(`SELECT ${fields} FROM courtyard WHERE id=?${publicOnly ? " AND review_status = 'verified' AND status = 1" : ''} LIMIT 1`, [id]); return rows[0] || null }
async function findByCandidateId(db, candidateId) { const [rows] = await db.query('SELECT id FROM courtyard WHERE candidate_id=? LIMIT 1', [candidateId]); return rows[0] || null }
async function insert(db, input) { const [result] = await db.query('INSERT INTO courtyard (candidate_id,name,aliases,description,content,historical_use,current_use,position_x,position_y,source_url,source_name,evidence,review_status,status,sort_order) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', [input.candidateId || null,input.name,input.aliases,input.summary,input.content,input.historicalUse,input.currentUse,input.positionX,input.positionY,input.sourceUrl,input.sourceName,input.evidence,input.reviewStatus,input.status,input.sortOrder]); return result.insertId }
async function update(db, id, input) { await db.query('UPDATE courtyard SET name=?,aliases=?,description=?,content=?,historical_use=?,current_use=?,position_x=?,position_y=?,source_url=?,source_name=?,evidence=?,review_status=?,status=?,sort_order=? WHERE id=?', [input.name,input.aliases,input.summary,input.content,input.historicalUse,input.currentUse,input.positionX,input.positionY,input.sourceUrl,input.sourceName,input.evidence,input.reviewStatus,input.status,input.sortOrder,id]) }
async function hide(db, id) { await db.query('UPDATE courtyard SET status=0 WHERE id=?', [id]) }
module.exports = { count, find, findByCandidateId, hide, insert, list, update }
