const fields = 'id, candidate_id, time_text, year, month, day, time_precision, title, description AS summary, content, image AS cover_image, source_url, source_name, evidence, review_status, status, is_featured, sort_order, created_at, updated_at'
function where(filters, publicOnly) { const conditions = []; const values = []; if (publicOnly) conditions.push("review_status = 'verified'", 'status = 1'); if (filters.featured) conditions.push('is_featured = 1'); if (filters.keyword) { conditions.push('(title LIKE ? OR time_text LIKE ? OR description LIKE ?)'); values.push(...Array(3).fill(`%${filters.keyword}%`)) } if (filters.reviewStatus) { conditions.push('review_status = ?'); values.push(filters.reviewStatus) } if (filters.status !== undefined) { conditions.push('status = ?'); values.push(filters.status) } if (filters.featured !== undefined && !publicOnly) { conditions.push('is_featured = ?'); values.push(filters.featured ? 1 : 0) } return { clause: conditions.length ? `WHERE ${conditions.join(' AND ')}` : '', values } }
async function list(db, filters, pagination, publicOnly = false) { const { clause, values } = where(filters, publicOnly); const [rows] = await db.query(`SELECT ${fields} FROM history_event ${clause} ORDER BY year IS NULL, year, month IS NULL, month, day IS NULL, day, sort_order, id LIMIT ? OFFSET ?`, [...values, pagination.pageSize, pagination.offset]); return rows }
async function count(db, filters, publicOnly = false) { const { clause, values } = where(filters, publicOnly); const [rows] = await db.query(`SELECT COUNT(*) AS total FROM history_event ${clause}`, values); return rows[0].total }
async function find(db, id, publicOnly = false) { const [rows] = await db.query(`SELECT ${fields} FROM history_event WHERE id = ?${publicOnly ? " AND review_status = 'verified' AND status = 1" : ''} LIMIT 1`, [id]); return rows[0] || null }
async function insert(db, input) { const [result] = await db.query('INSERT INTO history_event (time_text, year, month, day, event_date, time_precision, title, description, content, source_url, source_name, evidence, review_status, status, is_featured, sort_order) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [input.timeText,input.year,input.month,input.day,input.eventDate,input.timePrecision,input.title,input.summary,input.content,input.sourceUrl,input.sourceName,input.evidence,input.reviewStatus,input.status,input.isFeatured,input.sortOrder]); return result.insertId }
async function update(db, id, input) { await db.query('UPDATE history_event SET time_text=?, year=?, month=?, day=?, event_date=?, time_precision=?, title=?, description=?, content=?, source_url=?, source_name=?, evidence=?, review_status=?, status=?, is_featured=?, sort_order=? WHERE id=?', [input.timeText,input.year,input.month,input.day,input.eventDate,input.timePrecision,input.title,input.summary,input.content,input.sourceUrl,input.sourceName,input.evidence,input.reviewStatus,input.status,input.isFeatured,input.sortOrder,id]) }
async function hide(db, id) { await db.query('UPDATE history_event SET status = 0 WHERE id = ?', [id]) }
module.exports = { count, find, hide, insert, list, update }
