import client from './client.js'
export const getSite = () => client.get('/admin/digital-museum')
export const saveSite = (data) => client.put('/admin/digital-museum', data)
export const getList = (params) => client.get('/admin/courtyards', { params })
export const getById = (id) => client.get(`/admin/courtyards/${id}`)
export const create = (data) => client.post('/admin/courtyards', data)
export const update = (id, data) => client.put(`/admin/courtyards/${id}`, data)
export const remove = (id) => client.delete(`/admin/courtyards/${id}`)
export const getImages = (id) => client.get(`/admin/courtyards/${id}/images`)
export const uploadImage = (id, data) => client.post(`/admin/courtyards/${id}/images`, data)
export const updateImage = (id, imageId, data) => client.put(`/admin/courtyards/${id}/images/${imageId}`, data)
export const removeImage = (id, imageId) => client.delete(`/admin/courtyards/${id}/images/${imageId}`)
export const getSiteImages = (id) => client.get(`/admin/digital-museum/${id}/images`)
export const uploadSiteImage = (id, data) => client.post(`/admin/digital-museum/${id}/images`, data)
export const updateSiteImage = (id, imageId, data) => client.put(`/admin/digital-museum/${id}/images/${imageId}`, data)
export const removeSiteImage = (id, imageId) => client.delete(`/admin/digital-museum/${id}/images/${imageId}`)
