import client from './client.js'
export const getList = (params) => client.get('/admin/relics', { params })
export const getById = (id) => client.get(`/admin/relics/${id}`)
export const getCategories = () => client.get('/admin/relics/categories')
export const create = (data) => client.post('/admin/relics', data)
export const update = (id, data) => client.put(`/admin/relics/${id}`, data)
export const remove = (id) => client.delete(`/admin/relics/${id}`)
export const getImages = (id) => client.get(`/admin/relics/${id}/images`)
export const uploadImage = (id, data) => client.post(`/admin/relics/${id}/images`, data)
export const updateImage = (id, imageId, data) => client.put(`/admin/relics/${id}/images/${imageId}`, data)
export const removeImage = (id, imageId) => client.delete(`/admin/relics/${id}/images/${imageId}`)
