const RESERVATION_STATUS = Object.freeze({
  PENDING: 0,
  SUCCESS: 1,
  CANCELLED: 2,
  CHECKED_IN: 3,
  EXPIRED: 4,
})

const ACTIVE_RESERVATION_STATUSES = Object.freeze([
  RESERVATION_STATUS.PENDING,
  RESERVATION_STATUS.SUCCESS,
])

module.exports = { ACTIVE_RESERVATION_STATUSES, RESERVATION_STATUS }
