<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElButton, ElButtonGroup } from 'element-plus'
import { fetchOverview,fetchTrafficTrend,fetchPageRanking,fetchReservationStatistics,fetchReservationTrend,fetchPeriodDistribution } from '../api/statistics.js'
import { formatMetric } from '../utils/dashboardStatistics.js'
import StatCard from '../components/dashboard/StatCard.vue'
import TrafficTrendChart from '../components/dashboard/TrafficTrendChart.vue'
import PageRankingChart from '../components/dashboard/PageRankingChart.vue'
import ReservationStatusChart from '../components/dashboard/ReservationStatusChart.vue'
import ReservationTrendChart from '../components/dashboard/ReservationTrendChart.vue'
import PeriodDistributionChart from '../components/dashboard/PeriodDistributionChart.vue'
const days=ref(7); const panels=reactive(Object.fromEntries(['overview','traffic','ranking','reservations','reservationTrend','period'].map(key=>[key,{data:key==='overview'||key==='reservations'?{}:[],loading:false,errorMessage:''}])))
async function loadPanel(key,request){const panel=panels[key];panel.loading=true;panel.errorMessage='';try{panel.data=await request()}catch{panel.errorMessage=`${key==='overview'?'核心指标':key==='traffic'?'访问趋势':key==='ranking'?'页面排行':key==='reservations'?'预约状态':key==='reservationTrend'?'预约趋势':'时段分布'}加载失败`}finally{panel.loading=false}}
async function loadTrends(){await Promise.allSettled([loadPanel('traffic',()=>fetchTrafficTrend(days.value)),loadPanel('reservationTrend',()=>fetchReservationTrend(days.value))])}
async function loadDashboard(){await Promise.allSettled([loadPanel('overview',fetchOverview),loadPanel('traffic',()=>fetchTrafficTrend(days.value)),loadPanel('ranking',()=>fetchPageRanking(10)),loadPanel('reservations',fetchReservationStatistics),loadPanel('reservationTrend',()=>fetchReservationTrend(days.value)),loadPanel('period',fetchPeriodDistribution)])}
async function selectDays(value){days.value=value;await loadTrends()};onMounted(loadDashboard)
</script>
<template><section class="dashboard"><header class="dashboard__header"><div><p class="eyebrow">OPERATIONS OVERVIEW</p><h1>数据总览</h1><p>访客访问与预约运营概况</p></div><div class="dashboard__tools"><span>统计范围</span><ElButtonGroup><ElButton :type="days===7?'primary':'default'" @click="selectDays(7)">近7天</ElButton><ElButton :type="days===14?'primary':'default'" @click="selectDays(14)">近14天</ElButton><ElButton :type="days===30?'primary':'default'" @click="selectDays(30)">近30天</ElButton></ElButtonGroup><ElButton :loading="panels.overview.loading" @click="loadDashboard">刷新数据</ElButton></div></header><div class="dashboard__metrics"><StatCard label="总访问量（PV）" :value="formatMetric(panels.overview.data.totalPv)" hint="PV：页面被访问的次数" :loading="panels.overview.loading"/><StatCard label="独立访客（UV）" :value="formatMetric(panels.overview.data.totalUv)" hint="UV：匿名访客数量" :loading="panels.overview.loading"/><StatCard label="今日访问量" :value="formatMetric(panels.overview.data.todayPv)" :loading="panels.overview.loading"/><StatCard label="今日独立访客" :value="formatMetric(panels.overview.data.todayUv)" :loading="panels.overview.loading"/><StatCard label="预约总数" :value="formatMetric(panels.overview.data.totalReservations)" :loading="panels.overview.loading"/><StatCard label="有效预约" :value="formatMetric(panels.overview.data.activeReservations)" :loading="panels.overview.loading"/></div><p v-if="panels.overview.errorMessage" class="dashboard__error">{{panels.overview.errorMessage}}</p><article class="dashboard__card dashboard__card--wide"><h2>访问趋势</h2><TrafficTrendChart v-bind="panels.traffic"/></article><div class="dashboard__grid"><article class="dashboard__card"><h2>页面访问排行</h2><PageRankingChart v-bind="panels.ranking"/></article><article class="dashboard__card"><h2>预约状态分布</h2><ReservationStatusChart v-bind="panels.reservations"/></article></div><article class="dashboard__card dashboard__card--wide"><h2>预约趋势</h2><ReservationTrendChart v-bind="panels.reservationTrend"/></article><article class="dashboard__card dashboard__card--wide"><h2>预约时段分布</h2><PeriodDistributionChart v-bind="panels.period"/></article></section></template>
<style scoped>.dashboard{max-width:1400px;margin:auto}.dashboard__header{display:flex;justify-content:space-between;gap:24px;align-items:end;margin-bottom:28px}.dashboard h1,.dashboard h2{margin:0}.dashboard__header p:last-child{color:var(--muted);margin:8px 0 0}.dashboard__tools{display:flex;align-items:center;gap:10px;flex-wrap:wrap;color:var(--muted);font-size:.85rem}.dashboard__metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}.dashboard__card{margin-top:20px;padding:22px;background:var(--cream);border:1px solid var(--line)}.dashboard__card h2{font-size:1.12rem}.dashboard__grid{display:grid;grid-template-columns:1.25fr .75fr;gap:20px}.dashboard__error{color:#9b2020}@media(max-width:1180px){.dashboard__metrics{grid-template-columns:repeat(3,1fr)}}@media(max-width:760px){.dashboard__header,.dashboard__grid{display:block}.dashboard__tools{margin-top:18px}.dashboard__metrics{grid-template-columns:repeat(2,1fr)}.dashboard__card{padding:16px}}@media(max-width:430px){.dashboard__metrics{grid-template-columns:1fr}}</style>
