<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElButton, ElDialog, ElInput, ElMessage, ElPagination, ElTable, ElTableColumn, ElTag } from 'element-plus'
import * as api from '../api/adminPeople.js'
import AdminMediaAssetManager from '../components/AdminMediaAssetManager.vue'
import { toDisplayImageUrl } from '../utils/imageUrl.js'

const filters = reactive({ page: 1, pageSize: 10, keyword: '' }); const rows = ref([]); const total = ref(0); const loading = ref(false); const selected = ref(null); const detailVisible = ref(false); const mediaVisible = ref(false); const editVisible = ref(false); const saving = ref(false); const form = reactive({ id: null, name: '', summary: '', content: '', sourceUrl: '', status: 1 })
async function load() { loading.value = true; try { const data = await api.getList({ page: filters.page, pageSize: filters.pageSize, keyword: filters.keyword || undefined }); rows.value = data.list || []; total.value = data.total || 0 } catch { ElMessage.error('人物列表暂时无法加载。') } finally { loading.value = false } }
async function openDetail(row) { try { selected.value = await api.getById(row.id); detailVisible.value = true } catch { ElMessage.error('人物详情暂时无法加载。') } }
function openMedia(row) { selected.value = row; mediaVisible.value = true }
async function openEdit(row) { try { Object.assign(form, await api.getById(row.id)); editVisible.value = true } catch { ElMessage.error('人物资料暂时无法加载。') } }
async function save() { if (!form.name.trim()) return ElMessage.warning('姓名不能为空。'); saving.value = true; try { await api.update(form.id, form); editVisible.value = false; await load(); ElMessage.success('人物资料已保存。') } catch (error) { ElMessage.error(error.message || '保存失败。') } finally { saving.value = false } }
function search() { filters.page = 1; load() }
onMounted(load)
</script>
<template><section><div class="admin-page-heading"><div><p class="eyebrow">PEOPLE MANAGEMENT</p><h1>人物管理</h1></div><p>管理正式人物资料及来源可追溯的图片资源。</p></div><form class="admin-filters" @submit.prevent="search"><ElInput v-model="filters.keyword" clearable placeholder="搜索姓名或资料" /><ElButton type="primary" native-type="submit">查询</ElButton></form><div class="admin-table-wrap"><ElTable v-loading="loading" :data="rows"><ElTableColumn label="姓名" prop="name" min-width="130" /><ElTableColumn label="身份/摘要" prop="summary" min-width="230" /><ElTableColumn label="图片状态" min-width="110"><template #default="{ row }"><img v-if="row.image" class="person-thumb" :src="toDisplayImageUrl(row.image)" :alt="row.name" /><span v-else>无旧图片</span></template></ElTableColumn><ElTableColumn label="状态" width="100"><template #default="{ row }"><ElTag :type="row.status === 1 ? 'success' : 'info'">{{ row.status === 1 ? '展示中' : '已下线' }}</ElTag></template></ElTableColumn><ElTableColumn label="操作" width="210"><template #default="{ row }"><ElButton link type="primary" @click="openDetail(row)">查看</ElButton><ElButton link type="primary" @click="openEdit(row)">编辑</ElButton><ElButton link type="primary" @click="openMedia(row)">图片管理</ElButton></template></ElTableColumn></ElTable></div><div class="admin-pagination"><ElPagination v-model:current-page="filters.page" :page-size="filters.pageSize" layout="total, prev, pager, next" :total="total" @current-change="load" /></div><ElDialog v-model="detailVisible" title="人物资料" width="min(92vw,680px)"><dl v-if="selected" class="admin-detail-list"><div><dt>姓名</dt><dd>{{ selected.name }}</dd></div><div><dt>摘要</dt><dd>{{ selected.summary || '—' }}</dd></div><div><dt>资料来源</dt><dd>{{ selected.sourceUrl || '—' }}</dd></div></dl></ElDialog><ElDialog v-model="editVisible" title="编辑人物资料" width="min(94vw,720px)"><form class="person-form" @submit.prevent="save"><label>姓名<ElInput v-model="form.name" /></label><label>来源 URL<ElInput v-model="form.sourceUrl" /></label><label class="span-two">摘要<ElInput v-model="form.summary" type="textarea" :rows="3" /></label><label class="span-two">正文<ElInput v-model="form.content" type="textarea" :rows="8" /></label></form><template #footer><ElButton @click="editVisible=false">取消</ElButton><ElButton type="primary" :loading="saving" @click="save">保存</ElButton></template></ElDialog><ElDialog v-model="mediaVisible" :title="`${selected?.name || ''} · 图片管理`" width="min(96vw,980px)" destroy-on-close><AdminMediaAssetManager v-if="selected" entity-type="person" :entity-id="selected.id" :api="api" /></ElDialog></section></template>
<style scoped>.admin-page-heading{display:flex;justify-content:space-between;align-items:end;gap:24px;margin-bottom:28px}.admin-page-heading h1{margin:0}.admin-page-heading>p{margin:0;color:var(--muted)}.admin-filters{display:flex;gap:12px;margin-bottom:20px}.admin-filters :deep(.el-input){max-width:300px}.admin-table-wrap{overflow:auto;background:var(--cream);border:1px solid var(--line)}.person-thumb{width:54px;height:54px;object-fit:cover}.admin-pagination{display:flex;justify-content:flex-end;margin-top:20px}.admin-detail-list div{display:grid;grid-template-columns:110px 1fr;gap:14px;padding:10px 0;border-bottom:1px solid var(--line)}.admin-detail-list dd{margin:0;white-space:pre-wrap}.person-form{display:grid;grid-template-columns:1fr 1fr;gap:16px}.person-form label{display:grid;gap:7px}.span-two{grid-column:span 2}@media(max-width:640px){.admin-page-heading{display:block}.admin-page-heading>p{margin-top:10px}.person-form{grid-template-columns:1fr}.span-two{grid-column:auto}}</style>
