<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElButton, ElDialog, ElInput, ElMessage, ElOption, ElPagination, ElSelect, ElTable, ElTableColumn, ElTag } from 'element-plus'
import AdminMediaAssetManager from '../components/AdminMediaAssetManager.vue'
import * as api from '../api/adminDigitalMuseum.js'

const site = reactive({ id:null,title:'七贤庄',summary:'',content:'',sourceUrl:'',sourceName:'',evidence:'',reviewStatus:'pending',status:0 })
const filters=reactive({ page:1,pageSize:10,keyword:'',reviewStatus:'',status:'' }); const rows=ref([]); const total=ref(0); const editing=ref(false); const formVisible=ref(false); const mediaVisible=ref(false); const target=ref(null)
const blank=()=>({id:null,name:'',aliases:[],summary:'',content:'',historicalUse:'',currentUse:'',positionX:null,positionY:null,sourceUrl:'',sourceName:'',evidence:'',reviewStatus:'pending',status:0,sortOrder:0}); const form=reactive(blank())
async function load(){try{const result=await api.getList(filters);rows.value=result.list;total.value=result.total}catch{ElMessage.error('院落列表暂时无法加载。')}}
async function loadSite(){try{const result=await api.getSite();if(result)Object.assign(site,result)}catch{ElMessage.error('七贤庄整体资料暂时无法加载。')}}
async function saveSite(){try{const saved=await api.saveSite(site);Object.assign(site,saved);ElMessage.success('七贤庄整体资料已保存。')}catch(error){ElMessage.error(error.message||'保存失败。')}}
function create(){Object.assign(form,blank());editing.value=false;formVisible.value=true} async function edit(row){try{Object.assign(form,await api.getById(row.id));editing.value=true;formVisible.value=true}catch{ElMessage.error('院落资料暂时无法加载。')}}
async function save(){try{if(editing.value)await api.update(form.id,form);else await api.create(form);formVisible.value=false;await load();ElMessage.success('院落资料已保存。')}catch(error){ElMessage.error(error.message||'保存失败。')}} async function hide(row){try{await api.remove(row.id);await load();ElMessage.success('院落已隐藏。')}catch{ElMessage.error('隐藏失败。')}} function images(row){target.value=row;mediaVisible.value=true}
const mapApi={getImages:api.getSiteImages,uploadImage:api.uploadSiteImage,updateImage:api.updateSiteImage,removeImage:api.removeSiteImage}
onMounted(async()=>{await Promise.all([load(),loadSite()])})
</script>
<template><section class="admin-digital"><div class="admin-page-heading"><div><p class="eyebrow">DIGITAL MUSEUM MANAGEMENT</p><h1>数字纪念馆</h1></div><p>热点坐标仅用于前端视觉布局，不代表测绘或地理坐标；仅已核验且展示中的院落对游客公开。</p></div>
<article class="manager-section"><h2>七贤庄整体</h2><div class="form-grid"><label>名称<ElInput v-model="site.title"/></label><label>来源机构<ElInput v-model="site.sourceName"/></label><label class="wide">简介<ElInput v-model="site.summary" type="textarea"/></label><label class="wide">详细介绍<ElInput v-model="site.content" type="textarea"/></label><label>来源页面<ElInput v-model="site.sourceUrl"/></label><label>审核状态<ElSelect v-model="site.reviewStatus"><ElOption label="待核验" value="pending"/><ElOption label="已核验" value="verified"/><ElOption label="有冲突" value="conflict"/><ElOption label="不采用" value="rejected"/></ElSelect></label><label class="wide">证据摘要<ElInput v-model="site.evidence" type="textarea"/></label><label>展示状态<ElSelect v-model="site.status"><ElOption label="展示中" :value="1"/><ElOption label="隐藏" :value="0"/></ElSelect></label></div><ElButton type="primary" @click="saveSite">保存七贤庄整体资料</ElButton><div v-if="site.id" class="map-manager"><h3>导览底图</h3><p>可上传官方导览图，或将课程设计图明确标为“课程设计导览示意图，非测绘地图”。</p><AdminMediaAssetManager entity-type="digital_museum" :entity-id="site.id" :api="mapApi"/></div></article>
<article class="manager-section"><div class="section-title"><h2>院落与热点</h2><ElButton type="primary" plain @click="create">新增院落</ElButton></div><div class="filters"><ElInput v-model="filters.keyword" placeholder="搜索院落"/><ElSelect v-model="filters.reviewStatus" clearable placeholder="审核状态"><ElOption label="待核验" value="pending"/><ElOption label="已核验" value="verified"/><ElOption label="有冲突" value="conflict"/><ElOption label="不采用" value="rejected"/></ElSelect><ElButton type="primary" @click="filters.page=1;load()">查询</ElButton></div><ElTable :data="rows" stripe><ElTableColumn prop="name" label="院落" min-width="150"/><ElTableColumn prop="historicalUse" label="历史用途" min-width="180"/><ElTableColumn label="坐标" width="135"><template #default="{row}">{{row.positionX ?? '—'}}, {{row.positionY ?? '—'}}</template></ElTableColumn><ElTableColumn label="审核" width="100"><template #default="{row}"><ElTag>{{row.reviewStatus}}</ElTag></template></ElTableColumn><ElTableColumn label="展示" width="80"><template #default="{row}">{{row.status?'是':'否'}}</template></ElTableColumn><ElTableColumn label="操作" width="200" fixed="right"><template #default="{row}"><ElButton link @click="edit(row)">编辑</ElButton><ElButton link @click="images(row)">图片</ElButton><ElButton link type="danger" @click="hide(row)">隐藏</ElButton></template></ElTableColumn></ElTable><ElPagination v-model:current-page="filters.page" :page-size="filters.pageSize" layout="total,prev,pager,next" :total="total" @current-change="load"/></article>
<ElDialog v-model="formVisible" :title="editing?'编辑院落':'新增院落'" width="min(95vw,760px)"><div class="form-grid"><label>院落名称*<ElInput v-model="form.name"/></label><label>别名<ElInput :model-value="form.aliases?.join('、')" @update:model-value="form.aliases=$event.split(/[、，,]/).filter(Boolean)"/></label><label class="wide">简要介绍*<ElInput v-model="form.summary" type="textarea"/></label><label>历史用途<ElInput v-model="form.historicalUse"/></label><label>当前用途<ElInput v-model="form.currentUse"/></label><label>热点 X（0–100）<ElInput v-model.number="form.positionX" type="number" min="0" max="100"/></label><label>热点 Y（0–100）<ElInput v-model.number="form.positionY" type="number" min="0" max="100"/></label><label class="wide">详细内容<ElInput v-model="form.content" type="textarea"/></label><label>来源机构*<ElInput v-model="form.sourceName"/></label><label>来源 URL<ElInput v-model="form.sourceUrl"/></label><label class="wide">证据摘要*<ElInput v-model="form.evidence" type="textarea"/></label><label>审核状态<ElSelect v-model="form.reviewStatus"><ElOption label="待核验" value="pending"/><ElOption label="已核验" value="verified"/><ElOption label="有冲突" value="conflict"/><ElOption label="不采用" value="rejected"/></ElSelect></label><label>展示状态<ElSelect v-model="form.status"><ElOption label="展示中" :value="1"/><ElOption label="隐藏" :value="0"/></ElSelect></label><label>排序<ElInput v-model.number="form.sortOrder" type="number" min="0"/></label></div><template #footer><ElButton @click="formVisible=false">取消</ElButton><ElButton type="primary" @click="save">保存</ElButton></template></ElDialog><ElDialog v-model="mediaVisible" width="min(96vw,980px)" :title="`${target?.name||''} · 图片管理`"><AdminMediaAssetManager v-if="target" entity-type="courtyard" :entity-id="target.id" :api="api"/></ElDialog></section></template>
<style scoped>.admin-page-heading,.section-title{display:flex;justify-content:space-between;gap:22px;align-items:end}.admin-page-heading p{max-width:460px;color:var(--muted);line-height:1.7}.admin-page-heading h1,.manager-section h2{margin:0}.manager-section{margin-top:26px;padding:24px;background:var(--cream);border:1px solid var(--line)}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:18px 0}.form-grid label{display:grid;gap:6px}.wide{grid-column:span 2}.map-manager{margin-top:25px;padding-top:20px;border-top:1px solid var(--line)}.map-manager h3{margin:0}.map-manager p{color:var(--muted)}.filters{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.filters :deep(.el-input),.filters :deep(.el-select){width:220px}@media(max-width:680px){.admin-page-heading{display:block}.form-grid{grid-template-columns:1fr}.wide{grid-column:auto}.filters :deep(.el-input),.filters :deep(.el-select){width:100%}}</style>
